os: linux
dist: xenial
language: python
python:
  - '3.5'
before_install:
  - sudo apt-get install -y chromium-browser chromium-chromedriver
before_script:
  - pip install pipenv
  - pipenv install --dev

env:
  - DJANGO_SETTINGS_MODULE="cocktail_engine.settings"


script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - coverage run manage.py test engine -v 2
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 45dd26e0-2ebf-4153-a265-99862693e90a
