os: linux
dist: xenial
language: python
python:
  - '3.5'
before_install:
  - sudo apt-get install -y chromium-browser chromium-chromedriver
before_script:
  - pip install -r requirements.txt
  - pip install codecov

env: DJANGO_SETTINGS_MODULE="cocktail_engine.settings"


script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - ./manage.py test
after_success:
  - codecov --token="45dd26e0-2ebf-4153-a265-99862693e90a"
