os: linux
dist: xenial
language: python
python:
  - '3.5'
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="cocktail_engine.settings"


script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - ./manage.py test